### ISSUE TITLE
README.md Link not working

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [IDLabResearch/IFC-to-RDF-converter#13]
Dear Pieter, dear Jyrki,

apparently the link to some further documentation is not working anymore. Could you may be check whether this needs to be updated?

in README.md

> https://github.com/pipauwel/IFC-to-RDF-converter#using-the-gui

**Comment by jyrkioraskari** [comment]
The GUI part of the converter was moved to here:  https://github.com/jyrkioraskari/IFCtoRDF-Desktop

So, the READMe.md should be updated.

**Comment by pipauwel** [comment]
Great, and that https://github.com/jyrkioraskari/IFCtoRDF-Desktop relies on the newer code at https://github.com/pipauwel/IFCtoRDF. So, better not use this IDLabResearch repo any more, but use these two links / projects instead.
